<?php

/**
 * This file is autogenerated by Laragoon
 */

return [
    'default' => env('DB_CONNECTION', 'mysql'),
    'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('MARIADB_HOST', env('DB_HOST', 'mariadb')),
            'port' => env('MARIADB_PORT', env('DB_PORT', '3306')),
            'database' => env('MARIADB_DATABASE', env('DB_DATABASE', 'lagoon')),
            'username' => env('MARIADB_USERNAME', env('DB_USERNAME', 'lagoon')),
            'password' => env('MARIADB_PASSWORD', env('DB_PASSWORD', 'lagoon')),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
    ],
    'migrations' => 'migrations',
    'redis' => [
        'client' => 'predis',
        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],
    ],
];

